name: CI
on: push
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 14
    - name: Install dependencies 
      run: npm i
    - name: Lint
      run: npm run lint